//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public string AccountNumber { get; set; }
        public string CreditLimit { get; set; }
        public string ActualBalance { get; set; }
        public string AvailableBalance { get; set; }
        public Nullable<int> CustomerId { get; set; }
    }
}
