//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id { get; set; }
        public string product { get; set; }
        public string amount { get; set; }
        public Nullable<System.DateTime> transactionDate { get; set; }
        public string price { get; set; }
        public string unit { get; set; }
        public string paymentTerms { get; set; }
        public string paymentMode { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public Nullable<int> customerId { get; set; }
        public int rejectStatus { get; set; }
        public int paidStatus { get; set; }
    }
}
